application:
    build: code
    volumes:
        - ./app:/var/www/laravel
        - ./logs/laravel:/var/www/laravel/storage/logs
    tty: true
db:
    image: mysql:5.6
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: laravel
        TEST_DB_NAME: laravel_test
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
    volumes:
        - ./mysqldata/:/var/mysql/data
    ports:
        - 3306:3306
redis:
  image: redis:4.0-alpine
  ports:
      - 6379:6379
php:
    build: php7-fpm
    environment:
        MAIL_ENCRYPTION: 0
        MAIL_PRETEND: 0
        MAIL_USERNAME: null
        MAIL_PASSWORD: null
    volumes_from:
        - application
    links:
        - db
        - redis
nginx:
    build: nginx
    links:
        - php
    volumes_from:
        - application
    volumes:
        - ./logs/nginx/:/var/log/nginx
    ports:
        - 80:80